# File generated by stainful — DO NOT EDIT.
from __future__ import annotations

from functools import cached_property

import httpx

from .._core._request_options import make_request_options
from .._core._resource import AsyncAPIResource, SyncAPIResource
from .._core._response import (
    async_to_raw_response_wrapper,
    async_to_streamed_response_wrapper,
    to_raw_response_wrapper,
    to_streamed_response_wrapper,
)
from .._core._sentinels import NotGiven, not_given
from .._core._types import Body, Headers, Query
from ..types.agency_retrieve_response import AgencyRetrieveResponse

__all__ = ["Agency", "AsyncAgency"]


class Agency(SyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AgencyWithRawResponse:
        return AgencyWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AgencyWithStreamingResponse:
        return AgencyWithStreamingResponse(self)

    def retrieve(
        self,
        agency_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AgencyRetrieveResponse:
        """Retrieve info for a specific transit agency identified by ID."""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        return self._get(
            f"/api/where/agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=AgencyRetrieveResponse,
        )


class AsyncAgency(AsyncAPIResource):
    @cached_property
    def with_raw_response(self) -> AsyncAgencyWithRawResponse:
        return AsyncAgencyWithRawResponse(self)

    @cached_property
    def with_streaming_response(self) -> AsyncAgencyWithStreamingResponse:
        return AsyncAgencyWithStreamingResponse(self)

    async def retrieve(
        self,
        agency_id: str,
        *,
        extra_headers: Headers | None = None,
        extra_query: Query | None = None,
        extra_body: Body | None = None,
        timeout: float | httpx.Timeout | None | NotGiven = not_given,
    ) -> AgencyRetrieveResponse:
        """Retrieve info for a specific transit agency identified by ID."""
        if not agency_id:
            raise ValueError(
                f"Expected a non-empty value for `agency_id` but received {agency_id!r}"
            )
        return await self._get(
            f"/api/where/agency/{agency_id}.json",
            options=make_request_options(
                extra_headers=extra_headers,
                extra_query=extra_query,
                extra_body=extra_body,
                timeout=timeout,
            ),
            cast_to=AgencyRetrieveResponse,
        )


class AgencyWithRawResponse:
    def __init__(self, agency: Agency) -> None:
        self.retrieve = to_raw_response_wrapper(agency.retrieve)


class AsyncAgencyWithRawResponse:
    def __init__(self, agency: AsyncAgency) -> None:
        self.retrieve = async_to_raw_response_wrapper(agency.retrieve)


class AgencyWithStreamingResponse:
    def __init__(self, agency: Agency) -> None:
        self.retrieve = to_streamed_response_wrapper(agency.retrieve)


class AsyncAgencyWithStreamingResponse:
    def __init__(self, agency: AsyncAgency) -> None:
        self.retrieve = async_to_streamed_response_wrapper(agency.retrieve)
